apiVersion: v1
kind: Secret
metadata:
  name: castai-hibernate
  namespace: castai-agent
type: Opaque
data:
  API_KEY: >-
    Q0FTVEFJLUFQSS1LRVktUkVQTEFDRS1NRS1XSVRILUFCT1ZFLg==
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: hibernate
  namespace: castai-agent
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: castai-agent
  name: hibernate
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["*"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: hibernate
  namespace: castai-agent
subjects:
- kind: ServiceAccount
  name: hibernate
  apiGroup: ""
roleRef:
  kind: Role
  name: hibernate
  apiGroup: ""
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: hibernate
rules:
  - verbs:
      - get
      - list
      - patch
    apiGroups:
      - ''
    resources:
      - nodes
  - verbs:
      - get
    apiGroups:
      - ''
    resources:
      - namespaces
  - verbs:
      - get
      - list
      - delete
      - create
      - watch
    apiGroups:
      - ''
    resources:
      - events
  - verbs:
      - get
      - patch
      - update
      - delete
      - escalate
    apiGroups:
      - ''
    resources:
      - namespaces
    resourceNames:
      - castai-agent
      - kube-system
  - verbs:
      - get
      - list
      - patch
    apiGroups:
      - "apps"
    resources:
      - deployments
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: hibernate
subjects:
  - kind: ServiceAccount
    name: hibernate
    namespace: castai-agent
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: hibernate
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: hibernate-admin
subjects:
  - kind: ServiceAccount
    name: hibernate
    namespace: castai-agent
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: hibernate-pause
  namespace: castai-agent
spec:
  schedule: "0 22 * * 1-5"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          tolerations:
          - key: "scheduling.cast.ai/paused-cluster"
            operator: Exists
          serviceAccountName: hibernate
          containers:
          - name: pauser
            image: castai/hibernate:latest
            imagePullPolicy: Always
            envFrom:
              - secretRef:
                  name: castai-hibernate
            env:
              - name: CLOUD
                value: "AKS"
              - name: ACTION
                value: "pause"
              - name: CLUSTER_ID
                valueFrom:
                  configMapKeyRef:
                    name: castai-cluster-controller
                    key: CLUSTER_ID
          restartPolicy: Never
      backoffLimit: 1
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: hibernate-resume
  namespace: castai-agent
spec:
  schedule: "0 7 * * 1-5"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          tolerations:
          - key: "scheduling.cast.ai/paused-cluster"
            operator: Exists
          serviceAccountName: hibernate
          containers:
          - name: pauser
            image: castai/hibernate:latest
            imagePullPolicy: Always
            envFrom:
              - secretRef:
                  name: castai-hibernate
            env:
              - name: CLOUD
                value: "AKS"
              - name: ACTION
                value: "resume"
              - name: CLUSTER_ID
                valueFrom:
                  configMapKeyRef:
                    name: castai-cluster-controller
                    key: CLUSTER_ID
          restartPolicy: Never
      backoffLimit: 1
---